# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from shellev.api_helper import APIHelper


class ShellAPIPlatformSecurityAuthenticationControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(ShellAPIPlatformSecurityAuthenticationControllerTests, cls).setUpClass()
        cls.controller = cls.client.shell_api_platform_security_authentication
        cls.response_catcher = cls.controller.http_call_back

    # To obtain APIGEE access token
    def test_oauth_token_post(self):
        # Parameters for the API call
        grant_type = 'client_credentials'
        client_id = 'SOFflRakNlwnWlxfOXQ4GHDVyqGawuKA'
        client_secret = 'cRnWgw7gACqM3gVS'

        # Perform the API call through the SDK function
        result = self.controller.oauth_token_post(grant_type, client_id, client_secret)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


