# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from shellev.api_helper import APIHelper


class StationLocatorControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(StationLocatorControllerTests, cls).setUpClass()
        cls.controller = cls.client.station_locator
        cls.response_catcher = cls.controller.http_call_back

    # Returns all sites within specified radius of specified GPS location. Sites of all Types are returned. This call must be used when attempting to establish the station the user is located at as part of fuelling journey (i.e. user has to be within 300m of station to be considered located at the station). This API could also be used as a general query to find nearby Shell locations
    def test_stationlocator_v_1_stations_get_around_location(self):
        # Parameters for the API call
        m = 'aroundLocation'
        lon = 77.6730103
        lat = 12.9132169
        radius = 0.3
        offer_code = None
        n = None
        amenities = None
        countries = None

        # Perform the API call through the SDK function
        result = self.controller.stationlocator_v_1_stations_get_around_location(m, lon, lat, radius, offer_code, n, amenities, countries)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


