# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from shellev.api_helper import APIHelper


class FuelingControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(FuelingControllerTests, cls).setUpClass()
        cls.controller = cls.client.fueling
        cls.response_catcher = cls.controller.http_call_back

    # The Digital Payments Service enables 3rd Parties to trigger the refuel process which, if successful, will unlock a pump/nozzle ready for fuelling. Enables a 3rd party to request an access token to start using fueling.
    #   APIs
    def test_mpp_token(self):
        # Parameters for the API call
        grant_type = 'client_credentials'
        client_id = 'b2bmpp-cli'
        client_secret = 'f20935d8f14a44bd1f0923cc4c4fa63f7b25922330cd5080f735f1a2769ece77ce245cfe8ba4cbd2a58544ee5113c200b8e37a7be33311e4b6f3c785bf3f37d2'

        # Perform the API call through the SDK function
        result = self.controller.mpp_token(grant_type, client_id, client_secret)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # Enables a partner user to cancel pump reservation from the App
    def test_mpp_cancel_fueling(self):
        # Parameters for the API call
        mpp_transaction_id = '000000001C48'

        # Perform the API call through the SDK function
        self.controller.mpp_cancel_fueling(mpp_transaction_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

    # Enables a partner user to cancel pump reservation from the App
    def test_mpp_cancel_fueling_1(self):
        # Parameters for the API call
        mpp_transaction_id = '000000001C48'

        # Perform the API call through the SDK function
        self.controller.mpp_cancel_fueling(mpp_transaction_id)

        # Test response code
        assert self.response_catcher.response.status_code == 204

