# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellev.api_helper import APIHelper
from shellev.models.fault_response_fault_detail import FaultResponseFaultDetail


class FaultResponseFault(object):

    """Implementation of the 'faultResponseFault' model.

    TODO: type model description here.

    Attributes:
        faultstring (str): The description of the error.
        detail (FaultResponseFaultDetail): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "faultstring": 'faultstring',
        "detail": 'detail'
    }

    _optionals = [
        'faultstring',
        'detail',
    ]

    def __init__(self,
                 faultstring=APIHelper.SKIP,
                 detail=APIHelper.SKIP):
        """Constructor for the FaultResponseFault class"""

        # Initialize members of the class
        if faultstring is not APIHelper.SKIP:
            self.faultstring = faultstring 
        if detail is not APIHelper.SKIP:
            self.detail = detail 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        faultstring = dictionary.get("faultstring") if dictionary.get("faultstring") else APIHelper.SKIP
        detail = FaultResponseFaultDetail.from_dictionary(dictionary.get('detail')) if 'detail' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(faultstring,
                   detail)
