# -*- coding: utf-8 -*-

"""
shellsmartpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeEnum(object):

    """Implementation of the 'type' enum.

    Attributes:
        ENUM_0: The enum member of type int.
        ENUM_1: The enum member of type int.
        ENUM_2: The enum member of type int.
        ENUM_3: The enum member of type int.

    """
    ENUM_0 = 0

    ENUM_1 = 1

    ENUM_2 = 2

    ENUM_3 = 3

